=== BhandariJN/portfolio/jhamkanath2078/www/XML LAB/lib.dtd
<!ELEMENT Lib (book,block,libriain) >
<!ELEMENT book (books+)>
    <!ELEMENT block (blocks+)>
    <!ELEMENT libriain (fname, lname, doe)>

<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT doe (#PCDATA)>


<!ELEMENT books (bname, (author|writer),price, pubdate)>
<!ELEMENT bname (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT pubdate (#PCDATA)>

<!ELEMENT blocks (blockname, height, width, totalbook)>
<!ELEMENT blockname (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT totalbook (#PCDATA)>

=== BhandariJN/portfolio/jhamkanath2078/www/XML LAB/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Lib SYSTEM "lib.dtd">
<Lib>
    <book>
        <books>
            <bname>Ramayan</bname>
            <author>Balmiki</author>
            <price>1500</price>
            <pubdate>2053-05-02</pubdate>
        </books>
    </book>
    <block>
        <blocks>
            <blockname> Block A</blockname>
            <height>5'</height>
            <width>15'</width>
            <totalbook>500 </totalbook>
        </blocks>
    </block>
    <libriain>
            <fname> Hemraj</fname>
            <lname>Roka</lname>
            <doe>2044-5-25</doe>
    </libriain>
</Lib>
